"""Update models to reflect recent schema changes

Revision ID: 8e2b95fa81fb
Revises: 607d677d9932
Create Date: 2024-10-03 16:24:24.075887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e2b95fa81fb'
down_revision = '607d677d9932'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_index('ix_cards_rarity')
        batch_op.drop_index('ix_cards_set_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.create_index('ix_cards_set_code', ['set_code'], unique=False)
        batch_op.create_index('ix_cards_rarity', ['rarity'], unique=False)

    # ### end Alembic commands ###
