"""Remove import_record foreign key

Revision ID: c4c16fcaa592
Revises: 
Create Date: 2024-09-30 17:03:51.373292

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c4c16fcaa592'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('set_collection_counts',
    sa.Column('set_code', sa.Text(), nullable=False),
    sa.Column('collection_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['set_code'], ['sets.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('set_code')
    )
    op.drop_table('import_records')
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.alter_column('oracle_id',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('set_code',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_index('ix_cards_import_record_id')
        batch_op.drop_constraint('cards_import_record_id_fkey', type_='foreignkey')
        batch_op.drop_column('import_record_id')

    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.drop_constraint('sets_code_key', type_='unique')
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('sets_code_key', ['code'])

    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_record_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('cards_import_record_id_fkey', 'import_records', ['import_record_id'], ['id'])
        batch_op.create_index('ix_cards_import_record_id', ['import_record_id'], unique=False)
        batch_op.alter_column('set_code',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('oracle_id',
               existing_type=sa.TEXT(),
               nullable=False)

    op.create_table('import_records',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='import_records_pkey')
    )
    op.drop_table('set_collection_counts')
    # ### end Alembic commands ###
