"""Initial migration

Revision ID: c85a075a2a35
Revises: 
Create Date: 2024-09-26 21:53:39.735867

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c85a075a2a35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frame_effects', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('promo_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.alter_column('multiverse_ids',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using="multiverse_ids::jsonb")
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('collector_number',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('purchase_uris',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using="purchase_uris::jsonb")
        batch_op.drop_index('idx_cards_collector_number')
        batch_op.drop_index('idx_cards_colors_gin', postgresql_using='gin')
        batch_op.drop_index('idx_cards_name_trgm', postgresql_using='gin')
        batch_op.drop_index('idx_cards_prices', postgresql_using='gin')
        batch_op.drop_index('idx_cards_rarity')
        batch_op.drop_index('idx_cards_set_code')
        batch_op.drop_index('idx_cards_set_code_rarity')
        batch_op.drop_index('idx_cards_set_code_released_at')
        batch_op.drop_index('idx_cards_usd_foil_price')
        batch_op.drop_index('idx_cards_usd_price')
        batch_op.create_index(batch_op.f('ix_cards_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_oracle_id'), ['oracle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_rarity'), ['rarity'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_set_code'), ['set_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_type_line'), ['type_line'], unique=False)
        batch_op.create_foreign_key(None, 'sets', ['set_code'], ['code'])
        batch_op.drop_column('usd_foil_price')
        batch_op.drop_column('usd_price')

    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('code',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_index('idx_sets_code_unique')
        batch_op.drop_index('idx_sets_name_trgm', postgresql_using='gin')
        batch_op.drop_index('idx_sets_released_at')
        batch_op.drop_index('idx_sets_set_type')
        batch_op.create_index(batch_op.f('ix_sets_code'), ['code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sets_code'))
        batch_op.create_index('idx_sets_set_type', ['set_type'], unique=False)
        batch_op.create_index('idx_sets_released_at', ['released_at'], unique=False)
        batch_op.create_index('idx_sets_name_trgm', ['name'], unique=False, postgresql_using='gin')
        batch_op.create_index('idx_sets_code_unique', ['code'], unique=True)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('code',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usd_price', sa.NUMERIC(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('usd_foil_price', sa.NUMERIC(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_cards_type_line'))
        batch_op.drop_index(batch_op.f('ix_cards_set_code'))
        batch_op.drop_index(batch_op.f('ix_cards_rarity'))
        batch_op.drop_index(batch_op.f('ix_cards_oracle_id'))
        batch_op.drop_index(batch_op.f('ix_cards_name'))
        batch_op.create_index('idx_cards_usd_price', ['usd_price'], unique=False)
        batch_op.create_index('idx_cards_usd_foil_price', ['usd_foil_price'], unique=False)
        batch_op.create_index('idx_cards_set_code_released_at', ['set_code', sa.text('released_at DESC')], unique=False)
        batch_op.create_index('idx_cards_set_code_rarity', ['set_code', 'rarity'], unique=False)
        batch_op.create_index('idx_cards_set_code', ['set_code'], unique=False)
        batch_op.create_index('idx_cards_rarity', ['rarity'], unique=False)
        batch_op.create_index('idx_cards_prices', ['prices'], unique=False, postgresql_using='gin')
        batch_op.create_index('idx_cards_name_trgm', ['name'], unique=False, postgresql_using='gin')
        batch_op.create_index('idx_cards_colors_gin', ['colors'], unique=False, postgresql_using='gin')
        batch_op.create_index('idx_cards_collector_number', ['set_code', 'collector_number'], unique=False)
        batch_op.alter_column('purchase_uris',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('collector_number',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('multiverse_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('promo_types')
        batch_op.drop_column('frame_effects')

    # ### end Alembic commands ###
